version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=mytiffin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network

  app:
    build:
      context: .
      dockerfile: Dockerfile  # Specifies the Dockerfile for building the app
    container_name: node_app
    environment:
      - NODE_ENV=production
      - JWT_SECRET=yourjwtsecretkey          # Connects to the db service using its service name
      - DATABASE_URL="postgresql://postgres:test123@localhost:5432/mytiffin?schema=public"
      - PORT=5000
    ports:
      - "3000:3000"          # Expose port 3000 for the Express app
    depends_on:
      - db                    # Ensures db service is ready before starting the app
    volumes:
      - .:/app                # Mount the current directory to /app inside the container
    working_dir: /app         # Set working directory to /app
    networks:
      - db_network

volumes:
  postgres_data:

networks:
  db_network:
    driver: bridge
